name:                fine-grained-state
version:             0.1.0.0
github:              "tuura/fine-grained-state"
license:             BSD3
author:              "Georgy Lukyanov"
maintainer:          "mail@geo2a.info"
copyright:           "2019 Georgy Lukyanov"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/tuura/fine-grained-state#readme>

dependencies:
- base >= 4.7 && < 5
- bifunctors
- mtl
- list-t
- containers
- algebraic-graphs
- selective
- sbv
- units
- units-defs
- text
- pretty-simple
- smuggler

default-extensions:
- TypeFamilies
- TypeApplications
- TypeOperators
- DataKinds
- ScopedTypeVariables
- GeneralizedNewtypeDeriving
- DeriveFunctor
- StandaloneDeriving
- MultiParamTypeClasses
- KindSignatures
- ConstraintKinds
- FlexibleInstances
- FlexibleContexts
- GADTs
- RankNTypes
- OverloadedStrings
- LambdaCase
- MultiWayIf

ghc-options:
- -fwarn-incomplete-uni-patterns
- -fplugin=Smuggler.Plugin

library:
  source-dirs: src

