name:                fine-grained-state
version:             0.1.0.0
github:              "tuura/fine-grained-state"
license:             BSD3
author:              "Georgy Lukyanov"
maintainer:          "mail@geo2a.info"
copyright:           "2019 Georgy Lukyanov"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/tuura/fine-grained-state#readme>

dependencies:
- base >= 4.7 && < 5
- mtl
- containers
- selective
- sbv

default-extensions:
- TypeApplications
- ScopedTypeVariables
- DeriveFunctor
- StandaloneDeriving
- MultiParamTypeClasses
- KindSignatures
- ConstraintKinds
- FlexibleInstances
- GADTs
- RankNTypes
- OverloadedStrings
- LambdaCase
- MultiWayIf

library:
  source-dirs: src

